### ISSUE TITLE
游戏异常

### ISSUE THREAD

**Issue by nicewsc** [Evan8440/zhenxun_bot_HorseRace#1]
所有在同一时间段进行游戏的、不同的群的玩家会加入同一场对局：
举例：A群创建完角色并开始游戏，若B群有人在此时创建一个角色，那么这个角色会加入A群的游戏中
截图：A群内的情况（中间B群有人创建游戏角色）
![PP}`OT4I8964N6F8UXQ``@S](https://user-images.githubusercontent.com/59506907/175490178-7cca73e1-fb1d-4a12-932d-4382076cbdd5.png)

**Comment by nicewsc** [comment]
补充截图（程序日志）：
![EOPMWEP%FJA_H{`KWRL1@ 7](https://user-images.githubusercontent.com/59506907/175491190-26069735-dc84-42da-9d36-f03171100d51.png)

**Comment by Evan8440** [comment]
已更正是该死的脑回路和python的逻辑出现了偏离
