### ISSUE TITLE
马儿名字需要加入输入限制

### ISSUE THREAD

**Issue by wlz-remake** [Evan8440/zhenxun_bot_HorseRace#13]
群友起了几个比较特殊的名字：
1、 （空格）
2、...........
3、道具哦啊我i就带我今晚几点欧吉安我i但就怕叫我i的骄傲我就欧锦到我到欧文i多久哦哎加我啊见到我接到我的舰炮我见到我的骄傲我多久啊我发i无法解耦i而分手配件松平发饿哦i啊放假 金佛IASJEF爬进饿哦房管局哦i啊规划看到非农人口估计总不能iu整体哦改哦规划如果你想看见了吃饭不能批实在不好如果i白宫不过会这个和总决赛你的v与日本v还觉得不够客家人关闭u（很长的一段文本）

还有马儿可以重名

**Comment by Evan8440** [comment]
我理解了你们的群友做了啥
但我不理解
帮我传句话，做个人吧(╯‵□′)╯︵┻━┻

**Comment by Evan8440** [comment]
不过重名这事确实知道但没做限制

**Comment by Evan8440** [comment]
除了点一条 纯空格应该是没法识别的，不知道什么情况

**Comment by Evan8440** [comment]
其他的已经修复
