### ISSUE TITLE
已经添加了这个文件，还是提示找不到，依赖都安装了

### ISSUE THREAD

**Issue by Wxrmr** [Evan8440/zhenxun_bot_HorseRace#15]
![image](https://user-images.githubusercontent.com/106142304/179353048-c5e14234-cc5a-4e77-ba15-540f77988869.png)
![image](https://user-images.githubusercontent.com/106142304/179353059-57831210-e1fb-4da6-bdfc-ddf23d9669e9.png)

**Comment by Evan8440** [comment]
![image](https://user-images.githubusercontent.com/108109327/179353320-45afa008-7e3c-43b5-a52e-359f301b8d02.png)
有没有一种可能，我是说有可能
nonebot_plugin_htmlrender_main里有个文件夹叫nonebot_plugin_htmlrender

**Comment by Wxrmr** [comment]
![WU{H6%0_OEE49O9XQQXK@71](https://user-images.githubusercontent.com/106142304/179353436-656a31ba-b8e6-4c97-a0f6-1ad491885f51.jpg)
