### ISSUE TITLE
能不能加个赌注功能

### ISSUE THREAD

**Issue by fuyang0811** [Evan8440/zhenxun_bot_HorseRace#2]

**Comment by Evan8440** [comment]
![image](https://user-images.githubusercontent.com/108109327/175516414-a1685ffd-5a57-4e16-9b47-97cc7142c353.png)
你看过分类就能知道，我是有计划的

**Comment by Evan8440** [comment]
就暂时咕了而已，后续加

**Comment by heerheer** [comment]
不建议开放赌注功能，或者开放赌注后相关积分功能无法通过用户进行操作，即数据必须中心化，防止出现违法的行为。
（维护环境人人有责，宁可不开，也不要乱开了导致开发者进去。

**Comment by Evan8440** [comment]
早着呢，空有计划，这玩意一风控就幺蛾子_(:з」∠)_

**Comment by fuyang0811** [comment]
> 早着呢，空有计划，这玩意一风控就幺蛾子_(:з」∠)_

俄罗斯轮盘也算是赌注啊，我觉得应该没问题吧

**Comment by Evan8440** [comment]
俄罗斯转盘只有几个参数，就子弹在几号位，轮到谁什么了，而且是自带中断的，风控了玩家再次触发就行
但赛马的机制涉及的东西涉及太多，赛马宣布开始直接走循环体，早期测试的时候，到底哪里中断都能成迷直接查不出来的
这两能一样吗

**Comment by Evan8440** [comment]
21点和刮刮乐的数据体系和处理逻辑，最初就是以转盘作为参考设计的
那玩意我也算贼熟悉了，真觉得能做的请自行查看代码

**Comment by fuyang0811** [comment]
> 俄罗斯转盘只有几个参数，就子弹在几号位，轮到谁什么了，而且是自带中断的，风控了玩家再次触发就行 但赛马的机制涉及的东西涉及太多，赛马宣布开始直接走循环体，早期测试的时候，到底哪里中断都能成迷直接查不出来的 这两能一样吗

我以为你说的是容易被封这个风控，说涉及赌博什么的ψ(._. )>，咱两说的不是一个事。

**Comment by fuyang0811** [comment]
(＠_＠;)不是说这个很简单。

**Comment by Evan8440** [comment]
本项目完全开源，如有必要，请自行修改
这玩意程序上不好做，做不好不如不做，ok？
你是用户，不是甲方，我的计划表里这玩意排最后，我现在就不会做，仅此而已

**Comment by Evan8440** [comment]
涉及赌博啥的，我的群是第一个触及2^31（即数据库int值21亿的上限）的群，你觉得我在乎这个？群游戏的金币而已。

**Comment by fuyang0811** [comment]
> 本项目完全开源，如有必要，请自行修改 这玩意程序上不好做，做不好不如不做，ok？ 你是用户，不是甲方，我的计划表里这玩意排最后，我现在就不会做，仅此而已

???????我怎么你了，我没要求你，我在说我俩之间的误解，你怎么脾气就上来，离谱。简直了。

**Comment by Evan8440** [comment]
我已经说明白了，这玩意一堆bug，不好做，你要做你自己做啊
我说了我有计划加，ok？
游戏类发消息太多被风控也不是一天两天了，我暂时不想做，你追着我说这没意思哦

**Comment by fuyang0811** [comment]
1.我从来没有要求你做，你说了有计划后我就没再提这个事情，一直是你在提。
2.我只是说我原来理解错了你说的风控，给你解释一下。
我不知道你怎么理解的，上来被你怼了一通。
一个issue扯这么长也是绝了。就这样吧。拜拜。

**Comment by Evan8440** [comment]
《我从来没有要求你做》

![image](https://user-images.githubusercontent.com/108109327/176061158-7cf781c3-b62f-4206-b53d-8df1b8410d1b.png)

**Comment by Evan8440** [comment]
再见
