### ISSUE TITLE
事件包加载失败

### ISSUE THREAD

**Issue by chara1051** [Evan8440/zhenxun_bot_HorseRace#4]

**Comment by chara1051** [comment]
![Uploading mmexport1656120167387.png…]()

**Comment by chara1051** [comment]
![Uploading mmexport1656120167387.png…]()

**Comment by chara1051** [comment]
![捕获](https://user-images.githubusercontent.com/105768555/175753157-2a55bc60-bffe-43b3-893b-fda974010c1b.PNG)

**Comment by a930389426** [comment]
我将事件包的编码格式改回GBK就加载成功了

**Comment by Evan8440** [comment]
本体上次更新成了utf8了，因为pr新增的插件全都是默认utf8格式，哎嘿~

**Comment by chara1051** [comment]
> 我将事件包的编码格式改回GBK就加载成功了

谢谢，成功了

**Comment by chara1051** [comment]
> 本体上次更新成了utf8了，因为pr新增的插件全都是默认utf8格式，哎嘿~
![捕获](https://user-images.githubusercontent.com/105768555/175756657-2b97e3be-b69b-4073-9497-4cb70eef4f2f.PNG)
那大佬，这个咋办

**Comment by Evan8440** [comment]
下一份新的，__del__函数被我删了，是个历史残留问题
linux没出过问题，不知道什么情况，反正我寻思删掉就该没事了

**Comment by Evan8440** [comment]
Windows默认的gbk，代码里刚加了指定utf-8

**Comment by Gzcay** [comment]
Stand加载失败 其他都成功了

**Comment by Evan8440** [comment]
历史残留，不用在意（我已经把stand删了）

**Comment by Evan8440** [comment]
失败一个不影响其他的正常使用
