### ISSUE TITLE
游戏无法开始

### ISSUE THREAD

**Issue by q56535** [Evan8440/zhenxun_bot_HorseRace#7]
发送游戏开始之后控制台出现以下错误
![image](https://user-images.githubusercontent.com/26663837/175773693-c4d30420-acfa-43e0-a7a4-1d2457f8473c.png)

**Comment by Evan8440** [comment]
没遇到过，盲猜是事件没有成功导入导致事件数events_num = 0, 然后
random(0, -1)就报错了

**Comment by q56535** [comment]
是不是事件编码为utf8的原因，改gbk是不是可能就可以解决

**Comment by Evan8440** [comment]
管理员指令，赛马事件重载，确认是不是没有事件加载成功

**Comment by q56535** [comment]
我将事件改为gbk编码之后都可以加载成功，除了stand事件，utf8和gbk都没有办法成功加载

**Comment by Evan8440** [comment]
stand别管他，他群里和我说在别的群测试过了，结果猜猜里面有啥
中文冒号！！！

**Comment by Evan8440** [comment]
你是下的最新的吗，若过是老的或者不确定的话
看一下这里是不是有指定gbk还是没有参数
我想确认一下是Windows系统的json是不是默认gbk
![image](https://user-images.githubusercontent.com/108109327/175845746-9558550b-9535-4ce7-b812-e058615c2acd.png)

**Comment by q56535** [comment]
是最新的
![image](https://user-images.githubusercontent.com/26663837/175845953-bc327478-70b1-405e-a71d-7ade5dc42013.png)

**Comment by Evan8440** [comment]
那就是。。Windows的python默认gbk，_(:з」∠)_

**Comment by Evan8440** [comment]
我去把代码里默认utf8的代码加回来了，_(:з」∠)_

**Comment by q56535** [comment]
这是别的插件解析json的代码
![image](https://user-images.githubusercontent.com/26663837/175846758-8508ea02-b494-4401-83f6-837322b396f7.png)

**Comment by Evan8440** [comment]
我已经改过了，_(:з」∠)_是该死的Windows和linux差异
